### PR TITLE
~9x performance improvement in screen_grab and resize

### PR DESCRIPTION
**Pull request by dustinandrews**
Added window title search.
Keep win32 DC objects for re-use.
Moved resizing to win32 api.
Removed cv2 dependendancy from grabscreen.

Benchmark:
cv2 version
	%timeit screen = grab_screen(region=(0,40,1920,1120));screen = cv2.resize(screen, (480,270));screen = cv2.cvtColor(screen, cv2.COLOR_BGR2RGB)
	3500 µs ± 1230 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

win32 version
	%timeit screen = grab_screen(window_title='Spyder',region=(0,40,1920,1120),scale=0.25)
	388 µs ± 15.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

Thanks for the awesome project and in-depth explanations and code.
-Dustin (aka SaintD_1970)

### CODE REVIEW

**Comment by Sentdex** [comment]
Hmm, I get an attribute error

AttributeError: 'windows_screen_grab' object has no attribute '_hwnd'

I am seeing failure on the if search_str in getwindowtxt line, that is never True for me. 

For my window title substring I have 'Grand Theft Auto V'

**Comment by dustinandrews** [comment]
Yes, annoyingly I didn't test it very well! Sorry about that. I got the same error. Will make an update later. It's a problem with a missing _ on the first hwnd in the class.

________________________________

**Comment by dustinandrews** [comment]
Tested working now. Thank you for your patience. I wrote out data and was able to read it back and render it as an image. FYI: You can just pass a snip of the window title. Like 'Grand'.

**Comment by Sentdex** [comment]
Very cool, so NOW, how does one use this with open cv? I got it to find the window, and take a screenshot. Shape is (3, 270, 480), but I cannot do an cv2.imshow on it, since the channels comes first, not last. Okay, no problem, so next I do a 

screen = np.reshape(screen, (480, 270, 3))

... but now the image is all-white :(  

Ideas?

**Comment by dustinandrews** [comment]
Sorry for the slow response. I took a computer free break over the fourth. Hmm, I was able to view the channels with pyplots imshow when I tested it.


I've made some fixes and pushed my changes. Can you test with a command window just as a common baseline? I don't have GTA, but it's working with another game.

Some things I noticed:


  *   If you have the window minimized when you start the script it will get the wrong size and co-ordinates.

  *   If your game is full screen, I am not sure what will happen
  *   Some programs don't screenshot correctly, Chrome and Outlook for example. Chrome is just empty data and Outlook is missing a lot of data.
  *   Title bars sometimes don't show on screen the same as they report to windows. I put a "print" in the window handle enumeration to see them all.

I added a parameter for "window_handle" so you can use your same time delay strategy and just pass the window handle rather than a title. I hope that helps.



________________________________

**Comment by dustinandrews** [comment]
I also realized you may want to use np.swapaxes rather than reshape.


Try this instead:


channels_last = screenshot.swapaxes(0,2).swapaxes(0,1)

________________________________

**Comment by DanMossa** [comment]
@dustinandrews  Line 6 grabscreen.py

```
import win32ui
import win32gui
```

**Comment by Timotaam** [comment]
All you need to do if you want 'cv2' output is change the `get_rgb_from_bits` function to this:

`
    def get_rgb_from_bits(self, bits):
        """
        Reshape to rgb and strip the alpha channel.
        :parameter bits: numpy array in the format (r, g, b, a, r, g, b, a, ...)
        """    
        bits.shape = (self._dest_height,self._dest_width,4)
        self._rgb = bits
        return self._rgb
`

Though you might want to strip the alpha channel for size reasons? 

This is a really nice and fast solution, I like it

**Comment by dustinandrews** [comment]
I don't know what the Alpha channel would be good for in this use case so I just drop it to save memory and speed up saving to disk when I am done capturing.

________________________________

**Comment by Werseter** [comment]
At Line 123 in `get_screen_bits`
`self._memDC.StretchBlt((0,0), (self._dest_width, self._dest_height), self._windowDC, (0,0), (self._width,self._height), win32con.SRCCOPY) ` 

I think you meant
`self._memDC.StretchBlt((0,0), (self._dest_width, self._dest_height), self._windowDC, (self._top,self._left), (self._width,self._height), win32con.SRCCOPY)`

as otherwise it ignores the top/left positions and just proceeds to use only width/height provided through region.

**Comment by Werseter** [comment]
Combining this solution, with moving it to a different thread pull request by bb20basketball: [https://github.com/Sentdex/pygta5/pull/2](url)
allowed me to move from 3-4 FPS on my laptop, to around 50 FPS. Which I think, is quite impressive.

**Comment by Georggi** [comment]
@Werseter, do you have it properly working everywhere? In my case it works fine capturing PyCharm, but doesnt update anything(has only 1st ever frame) when capturing War Thunder.

**Comment by Werseter** [comment]
@Georggi Yes, I was also trying to convert it so I could record various parts of screen at different threads, but thats WIP and put aside for now. I've attempted to cut out the code fpr you so only relevant parts have stayed, haven't tested it. 

[getFrame.txt](https://github.com/Sentdex/pygta5/files/1449899/getFrame.txt)
[grabscreen.txt](https://github.com/Sentdex/pygta5/files/1449900/grabscreen.txt)
[buffedmain.txt](https://github.com/Sentdex/pygta5/files/1449901/buffedmain.txt)

I've heard Frenchies have arrived in WT ;) Tho I don't play it no more.

**Comment by Georggi** [comment]
It just became a bit choppy without this when playing;), getting only 30 fps with threading.

**Comment by Georggi** [comment]
Thanks, will test it at the weekend.

**Comment by christjosh4** [comment]
Okay

**Comment by renderedSafe** [comment]
I am running the latest version of this pull request and when checking the output at a random index, it always is a black screen with little bits of color at the edges. The values in the array seem to match up too.

I'm using the vanilla output from the code, and then checking the results with the `img.swapaxes(0,2).swapaxes(0,1)`
It seems to work sort of for other windows, but always gives me this output for GTA. Any ideas?

**Comment by Werseter** [comment]
Have you tried using the *messed around* code I've posted above? I've also completed the aforementioned threading part of the code, successfully used in two projects so far.

**Comment by Werseter** [comment]
After correctly threading the areas and keeping track of objects lifespan, I needed to introduce an FPS limiter, because I've reached too many frame reads thanks to combined efforts. I might make a pull request with updated code.

**Pull request closed without merging**
