### PR TITLE
Screenshot actual window coordinates

### PR DESCRIPTION
**Pull request by mdelcambre**
Screenshots the GTA V window based on the title of the window using the pywin32 for the screenshot. When screenshotting by the title, it will automatically calculate the width and height of the title bar and border to crop out. Additionally when screenshotting based on title, it will grab the actual window, even if buried underneath other windows.

Unlike #22, this still uses the faster screenshot of grab screen. I also believe #22 does not crop the title bar.

Limitation: I believe this breaks on full screen, but works flawlessly for me on window and borderless window.

### CODE REVIEW

**Comment by mdelcambre** [comment]
Unlike #22, this still uses the faster screenshot of grab screen. Additionally, without testing I am not sure #22 will automatically remove the titlebar for different versions of windows.

**Comment by Sentdex** [comment]
Hmm for some reason I get a black screen. It's finding the window, is in windowed mode, on main monitor, and at the forefront. Not sure what would cause this.

**Comment by mdelcambre** [comment]
Yeah, as we discussed, I think it is because of monitor scaling. I don't have an easy way to test that :(

**Comment by mdelcambre** [comment]
Okay, you can try this now. It requires you to play in borderless window, and it no longer is able screenshot when it is not on top.

**Comment by DanMossa** [comment]
@mdelcambre This works perfectly for me. Thanks mate!

**Pull request closed without merging**
