### PR TITLE
Code improvements and settings module

### PR DESCRIPTION
**Pull request by ramonsaraiva**
Improved some logic in different areas of the codebase, fixed some flake8 issues and created a module to store settings and definitions to be used across the the project.

Still have to go through other files, but i'm submitting this PR since it can conflict a lot with other code and it would be good to get it merged as soon as possible (if you like the changes).

Please let me know if you want to change anything.

I also couldn't test everything, so you should probably merge it locally and test it before.

### CODE REVIEW

**Comment by ramonsaraiva** [comment]
Sorry about that, totally forgot to stage the settings file.

The imports, spacing and all "style" related changes are pep8 friendly (pep8 is a style guide for python code), and it is pretty good to follow it.

I still want to go through the whole codebase and improve whatever i can, but i made the changes during a work break and didn't want to hold them.. The chances of conflicting code when changing styles and those kind of things is big.

**Comment by ramonsaraiva** [comment]
Also just saw that we could simplify a lot the logic behind the `key_check` function.
Please make sure you test the code before merging it, i can not fully test it cause i'm not on my PC.

**Comment by Sentdex** [comment]
Genuinely curious where in PEP 8 the parenthesis on the imports are? I assumed you were following PEP 8, but just never seen the parenthesis in PEP 8 I must be missing out on something.

**Comment by ramonsaraiva** [comment]
It's one of the ways to import many things from one module. I usually use cause the number of things you import normally grows and will need to go to the next line (If you follow the nax characters per line, of course).

Anyway, if the parentheses are the only thing blocking the PR to get merged, i can commit the removal of them.

Please let me know :)

**Comment by imallenyang** [comment]
For mac, If you use PIL to take screenshot, it will take almost 1 second to grab the image and use imshow to display, but if you use os.system("screencapture -x -R 0, 40, 800, 600 screen.png") then use imshow to show the picture, it will be much faster, approximately 10 frames per second.

**Comment by ramonsaraiva** [comment]
This is unfortunately one of the worst experiences i've had when trying to contribute to something. @Sentdex any feedback or conclusions on this?

**Pull request closed without merging**
