### PR TITLE
Added XInput Functionality

### PR DESCRIPTION
**Pull request by bayangan1991**
I will preface this by saying I don't know if this is the correct implementation. I am sure you will be able to read what I have written and correct it.

What I can say though is I have made a library that is able to report the analog input from a controller for the purposes of training the model.

and...

This library is also capable of creating a virtual controller and sending analog values to the GTA client (or any other xbox controller accepting game). Make sure you disconnect your controller so it takes the player 1 slot.

There is just one installation to be done for a Virtual USB driver. Run "PYXInput\ScpVBus-x64\install.bat" in an administation cmd prompt (Double click doesn't have permissions and R-Click run as admin doesn't work)

### CODE REVIEW

**Comment by Flandan** [comment]
This sounds brilliant @bayangan1991. It looks like a more complete solution than the one I am using, especilly if it works with gta v. I will be sure to give it a try.

**Comment by bayangan1991** [comment]
Thanks @flandan. Don't take it from here though. I have made it an installable package at https://github.com/bayangan1991/PYXInput

**Comment by bayangan1991** [comment]
Hey @Sentdex, probably best not to merge this, I have made some changes which I think make this a lot easier to use. You can also install it via PIP as well.

See: https://github.com/bayangan1991/PYXInput

**Comment by bayangan1991** [comment]
Woops, didn't mean to close completely!

**Comment by Flandan** [comment]
Even better. I'll give this a go sometime today.

**Comment by bayangan1991** [comment]
Awesome. Let me know how you go!

**Comment by Flandan** [comment]
I am having some trouble with installing this, I have posted an issue on the repository.
Cheers

**Comment by bayangan1991** [comment]
Closing this because its old code, See https://github.com/bayangan1991/PYXInput for a working copy

**Pull request closed without merging**
